import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
        <body className={`${inter.className} bg-purple-2`}>{children}</body>
        </html>
     </ClerkProvider>
  );
}
